@doskey cat=type $*
@doskey ls=dir /b $*
@doskey l=dir /od/p/q/tw $*
@doskey e.=explorer .
@doskey ls1=ls --show-control-chars -F --color $*
@doskey pwd=cd
@doskey clear=cls
@doskey g=git $1
@doskey ga=git add $1
@doskey ga.=git add .
@doskey gamend=git commit -C head -a --amend
@doskey gb=git branch
@doskey gc=git checkout $1
@doskey gch.=git checkout head .
@doskey gcl=git config --list
@doskey gcm=git commit -m $1 -a
@doskey gcmf=git commit -m $1 $2
@doskey gcp=git cherry-pick -n $1
@doskey gl=git log --oneline --all --graph --decorate  $*
@doskey glog=git log
@doskey gpl=git pull
@doskey gps=git push origin $1
@doskey gr=git reflog
@doskey gs=git show
@doskey gsd=git show $1 $2>$3
@doskey gsf=git show $1:$2>$3
@doskey gsta=git status